### DISCUSSION TITLE
Can I build from a specific tag on the same `master` branch?

### DISCUSSION THREAD

**Discussion by zhuoqun-chen** [nickcoutsos/keymap-editor#186] [Q&A] [answered]
Hello Developer!

Thank you for maintaining this great project!

I have a question: Can I build from a specific tag on the same `master` branch? Or I simply just add another `github action` to checkout to a specific tag, say `0.0.1` an then use the original:

```yaml
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
```

should be working and build the `firmware` for this tag?

**Comment by nickcoutsos** [comment]
Hi there.

The keymap editor itself doesn't actually handle building the firmware, it just integrates with GitHub APIs to link to the most recently completed build.

If you're talking about building from a specific ZMK version, look at your repository's `config/west.yml` which will look something like:

```
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
```

You can specify the tag name after `revision:` instead of `main`
