### ISSUE TITLE
Feature Request: Print Layout Screen.

### ISSUE THREAD

**Issue by tbandtg** [nickcoutsos/keymap-editor#114]
Would be nice to have it generate a set of png files of the layout created.

**Comment by calumy** [comment]
A workaround, for now, could be to use [caksoylar/keymap-drawer](https://github.com/caksoylar/keymap-drawer). It produces an SVG of the layout created e.g. https://github.com/calumy/zmk-config/blob/main/assets/lily58.svg. There is a workflow that can be used to generate the image every time you make a change:

```yaml
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      output_folder: "assets"
      commit_message: "Update keymap images"
```

For an example of how this could be used, take a look at: https://github.com/calumy/zmk-config/blob/main/.github/workflows/main_update.yml.
