### ISSUE TITLE
missing Mouse move behavior

### ISSUE THREAD

**Issue by achtan** [nickcoutsos/keymap-editor#241]
Hi, I cloned this layout from Ben: https://github.com/achtan/zmk-config-from-ben
and there I can see the "Mouse move behavior" 
<img width="649" alt="Screenshot 2024-07-18 at 12 28 58" src="https://github.com/user-attachments/assets/714891fb-4d2c-430b-bcab-ca5b1a66f1fd">

how every In my own repo: https://github.com/achtan/zmk-corne-5-col
I don't see that option...
How can I setup the Mouse move behavior?

**Comment by nickcoutsos** [comment]
Mouse movement stuff is (I think) not yet merged into ZMK main so you'll need to enable it as an experimental feature (don't forget to update your `westl.yml` accordingly). See https://github.com/nickcoutsos/keymap-editor/wiki/Experimental-ZMK-Features#mouse-emulation

**Comment by alehano** [comment]
> Mouse movement stuff is (I think) not yet merged into ZMK main so you'll need to enable it as an experimental feature (don't forget to update your `westl.yml` accordingly). See https://github.com/nickcoutsos/keymap-editor/wiki/Experimental-ZMK-Features#mouse-emulation

Please, help. How exactly should I update west.yml to be able to use mouse feature?

**Comment by nickcoutsos** [comment]
Your `config/west.yml` file should look something like:

```yaml
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
```

If you wanted to use the implementation in https://github.com/zmkfirmware/zmk/pull/778 for example, you might change it like so:

```patch
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
+    - name: krikun98
+    - url-base: https://github.com/krikun98
  projects:
    - name: zmk
-      remote: zmkfirmware
-      revision: main
+      remote: zmkfirmware
+      revision: mouse-pr
      import: app/west.yml
  self:
    path: config
```
